{"name": "Test for log in that failed", "status": "passed", "steps": [{"name": "Opening myAccountPage", "status": "passed", "start": 1696187702633, "stop": 1696187703429}, {"name": "Login with the username - 'test-qa-orginal@gmail.com' and password", "status": "passed", "parameters": [{"name": "username", "value": "'test-qa-orginal@gmail.com'"}, {"name": "password", "value": "'test'"}], "start": 1696187703429, "stop": 1696187704159}, {"name": "Getting error message", "status": "passed", "start": 1696187704159, "stop": 1696187704176}], "attachments": [{"name": "log", "source": "70eb66d5-f2b4-4216-9790-81c5738dd6b1-attachment.txt", "type": "text/plain"}], "start": 1696187702633, "stop": 1696187704176, "uuid": "e8036ee2-476a-4f79-b09d-8d3fce46cf9f", "historyId": "46e942d93486254f5e2dbb4c0da77afc", "testCaseId": "46e942d93486254f5e2dbb4c0da77afc", "fullName": "tests.login_test.TestLogIn#test_log_in_failed", "labels": [{"name": "tag", "value": "@pytest.mark.usefixtures('setup')"}, {"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "login_test"}, {"name": "subSuite", "value": "TestLogIn"}, {"name": "host", "value": "LAPTOP-ONODLJBO"}, {"name": "thread", "value": "19948-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.login_test"}]}